[files]
directories = ["src", "src/img", "bin"]
templates = [
                "bin/gitinfo-hook", "bin/create-hook-symlinks.sh",
                "src/autobib.bib", "src/JHEP.bst", "src/main.tex",
                ]

[config]
version = ""
