[files]
directories = ["src", "src/tex", "src/img", "bin"]
templates = [
                ".gitignore",
                "bin/gitinfo-hook", "bin/create-hook-symlinks.sh",
                "src/autobib.bib", "src/JHEP.bst",
                "src/mystyle.sty",
                "src/main.tex",
                "src/macros.sty",
                "src/tex/intro.tex",
                ]

[config]
version = ""
version_control = "git"
